/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_cwmobi_cp_Native */

#ifndef _Included_com_cwmobi_cp_Native
#define _Included_com_cwmobi_cp_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cwmobi_cp_Native
 * Method:    a
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_cwmobi_cp_Native_a
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
